import type { Service, Client, Appointment, Chat } from "./types";

export const SERVICES: Service[] = [
  {
    id: "s1",
    name: "Corte y peinado",
    duration: 60,
    price: 3500,
    color: "#9b7e7e",
    visible: true,
    category: "Corte",
  },
  {
    id: "s2",
    name: "Coloración completa",
    duration: 120,
    price: 8500,
    color: "#7e8e9b",
    visible: true,
    category: "Color",
  },
  {
    id: "s3",
    name: "Mechas balayage",
    duration: 150,
    price: 12000,
    color: "#9b9b7e",
    visible: true,
    category: "Color",
  },
  {
    id: "s4",
    name: "Tratamiento keratina",
    duration: 180,
    price: 15000,
    color: "#7e9b8e",
    visible: true,
    category: "Tratamiento",
  },
  {
    id: "s5",
    name: "Manicura express",
    duration: 45,
    price: 2200,
    color: "#b08080",
    visible: true,
    category: "Uñas",
  },
  {
    id: "s6",
    name: "Pedicura spa",
    duration: 60,
    price: 2800,
    color: "#9b7eb0",
    visible: false,
    category: "Uñas",
  },
];

export const CLIENTS: Client[] = [
  {
    id: "c1",
    name: "Ana García",
    initials: "AG",
    phone: "+54 9 11 4523-1234",
    email: "ana.garcia@email.com",
    visits: 12,
    totalSpent: 87500,
    lastVisit: "2026-04-28",
    notes: "Prefiere tinte sin amoníaco. Alérgica al látex.",
  },
  {
    id: "c2",
    name: "Beatriz Morales",
    initials: "BM",
    phone: "+54 9 11 3321-5678",
    email: "bea.morales@email.com",
    visits: 8,
    totalSpent: 62000,
    lastVisit: "2026-05-01",
    notes: "Le gusta el café cuando llega.",
  },
  {
    id: "c3",
    name: "Carolina Pérez",
    initials: "CP",
    phone: "+54 9 11 2298-9012",
    email: "caro.perez@email.com",
    visits: 3,
    totalSpent: 19500,
    lastVisit: "2026-04-15",
    notes: "",
  },
  {
    id: "c4",
    name: "Daniela Ruiz",
    initials: "DR",
    phone: "+54 9 11 6677-3456",
    email: "daniela.r@email.com",
    visits: 22,
    totalSpent: 143000,
    lastVisit: "2026-05-03",
    notes: "Cliente VIP. Reservar siempre martes o jueves.",
  },
  {
    id: "c5",
    name: "Elena Torres",
    initials: "ET",
    phone: "+54 9 11 9988-7654",
    email: "elena.torres@email.com",
    visits: 5,
    totalSpent: 34500,
    lastVisit: "2026-04-20",
    notes: "",
  },
  {
    id: "c6",
    name: "Fernanda López",
    initials: "FL",
    phone: "+54 9 11 5544-2109",
    email: "fer.lopez@email.com",
    visits: 15,
    totalSpent: 98000,
    lastVisit: "2026-04-30",
    notes: "Siempre paga en efectivo.",
  },
  {
    id: "c7",
    name: "Gabriela Soto",
    initials: "GS",
    phone: "+54 9 11 1122-8765",
    email: "gabi.soto@email.com",
    visits: 1,
    totalSpent: 3500,
    lastVisit: "2026-05-05",
    notes: "Primera visita hoy.",
  },
];

export const TODAY_APPTS: Appointment[] = [
  {
    id: "a1",
    clientId: "c1",
    clientName: "Ana García",
    clientPhone: "+54 9 11 4523-1234",
    serviceId: "s1",
    serviceName: "Corte y peinado",
    date: "2026-05-05",
    time: "09:00",
    duration: 60,
    price: 3500,
    status: "confirmed",
  },
  {
    id: "a2",
    clientId: "c4",
    clientName: "Daniela Ruiz",
    clientPhone: "+54 9 11 6677-3456",
    serviceId: "s3",
    serviceName: "Mechas balayage",
    date: "2026-05-05",
    time: "10:30",
    duration: 150,
    price: 12000,
    status: "confirmed",
  },
  {
    id: "a3",
    clientId: "c2",
    clientName: "Beatriz Morales",
    clientPhone: "+54 9 11 3321-5678",
    serviceId: "s2",
    serviceName: "Coloración completa",
    date: "2026-05-05",
    time: "14:00",
    duration: 120,
    price: 8500,
    status: "pending",
  },
  {
    id: "a4",
    clientId: "c7",
    clientName: "Gabriela Soto",
    clientPhone: "+54 9 11 1122-8765",
    serviceId: "s1",
    serviceName: "Corte y peinado",
    date: "2026-05-05",
    time: "16:30",
    duration: 60,
    price: 3500,
    status: "confirmed",
  },
];

export const ALL_APPTS: Appointment[] = [
  ...TODAY_APPTS,
  {
    id: "a5",
    clientId: "c3",
    clientName: "Carolina Pérez",
    clientPhone: "+54 9 11 2298-9012",
    serviceId: "s5",
    serviceName: "Manicura express",
    date: "2026-05-04",
    time: "11:00",
    duration: 45,
    price: 2200,
    status: "completed",
  },
  {
    id: "a6",
    clientId: "c6",
    clientName: "Fernanda López",
    clientPhone: "+54 9 11 5544-2109",
    serviceId: "s4",
    serviceName: "Tratamiento keratina",
    date: "2026-05-04",
    time: "09:30",
    duration: 180,
    price: 15000,
    status: "completed",
  },
  {
    id: "a7",
    clientId: "c5",
    clientName: "Elena Torres",
    clientPhone: "+54 9 11 9988-7654",
    serviceId: "s1",
    serviceName: "Corte y peinado",
    date: "2026-05-03",
    time: "15:00",
    duration: 60,
    price: 3500,
    status: "cancelled",
  },
  {
    id: "a8",
    clientId: "c2",
    clientName: "Beatriz Morales",
    clientPhone: "+54 9 11 3321-5678",
    serviceId: "s1",
    serviceName: "Corte y peinado",
    date: "2026-05-06",
    time: "10:00",
    duration: 60,
    price: 3500,
    status: "pending",
  },
];

export const CHATS: Chat[] = [
  {
    id: "ch1",
    clientId: "c1",
    clientName: "Ana García",
    lastMessage: "Perfecto, ¡hasta mañana!",
    lastTime: "10:42",
    unread: 0,
    isBot: false,
    messages: [
      {
        id: "m1",
        sender: "bot",
        text: "Hola Ana! Te recuerdo que tu turno de Corte y peinado es mañana martes a las 09:00. ¿Confirmas?",
        time: "10:30",
      },
      { id: "m2", sender: "them", text: "Sí, confirmo. Gracias!", time: "10:41" },
      { id: "m3", sender: "them", text: "Perfecto, ¡hasta mañana!", time: "10:42" },
    ],
  },
  {
    id: "ch2",
    clientId: "c4",
    clientName: "Daniela Ruiz",
    lastMessage: "¿Puedo cambiar el horario?",
    lastTime: "09:15",
    unread: 2,
    isBot: false,
    messages: [
      {
        id: "m4",
        sender: "bot",
        text: "Hola Daniela! Recordamos tu turno de Mechas balayage hoy a las 10:30.",
        time: "09:00",
      },
      {
        id: "m5",
        sender: "them",
        text: "¿Puedo cambiar el horario?",
        time: "09:15",
      },
      {
        id: "m6",
        sender: "me",
        text: "Claro Daniela, ¿qué horario te viene mejor?",
        time: "09:20",
      },
    ],
  },
  {
    id: "ch3",
    clientId: "c7",
    clientName: "Gabriela Soto",
    lastMessage: "¡Quiero sacar un turno!",
    lastTime: "Ayer",
    unread: 1,
    isBot: true,
    messages: [
      { id: "m7", sender: "them", text: "Hola! ¿Hacen corte de puntas?", time: "Ayer 18:00" },
      {
        id: "m8",
        sender: "bot",
        text: "Hola! Claro que sí. Ofrecemos Corte y peinado (60 min, $3.500). Para reservar puedes escribir TURNO o seguir el link.",
        time: "Ayer 18:01",
      },
      { id: "m9", sender: "them", text: "¡Quiero sacar un turno!", time: "Ayer 18:05" },
    ],
  },
  {
    id: "ch4",
    clientId: "c6",
    clientName: "Fernanda López",
    lastMessage: "Muchas gracias Marina, quedó re lindo",
    lastTime: "Lun",
    unread: 0,
    isBot: false,
    messages: [
      {
        id: "m10",
        sender: "them",
        text: "Muchas gracias Marina, quedó re lindo",
        time: "Lun 17:30",
      },
      { id: "m11", sender: "me", text: "Gracias a vos Fer! Hasta la próxima 🌸", time: "Lun 17:35" },
    ],
  },
];
